version: '3.8'

services:
  db:
    container_name: mysql-container
    image: mysql:8.0
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - ./.env.dev
    environment:
      - MYSQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
      - MYSQL_USER=${SQL_USER}
      - MYSQL_PASSWORD=${SQL_PASSWORD}
      - MYSQL_DATABASE=${SQL_DATABASE}
    #MySQL container's port 3306 (the default MySQL port) to the host machine's port 3307.
    ports:
      - 3307:3306

  web:
    container_name: django-web
    build:
      context: ./ml_app
      dockerfile: Dockerfile
    #important to note that running the Django development server with 0.0.0.0:8000 is intended 
    #for development and testing purposes only. In a production environment, it's recommended to 
    #use a dedicated web server like Nginx or Apache to serve your Django application, with the 
    #Django application running behind a reverse proxy or load balancer.
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./ml_app/:/usr/src/ml_app/
    env_file:
      - ./.env.dev
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db
